# Generated by Django 4.2.5 on 2023-11-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_customer_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
